separating docker compose for pmml and mlflow
prinz-nussknacker/prinz pull request #115
Opened 2021-03-04 23:58 UTC by Jadw1

create_environment.sh can now take arguments. By default, with no arguments it creates environment with all frameworks. However you can specify framework to launch e.g. `./create_environment.sh mlflow` will create environment with only mlflow framework.

`./create_environment.sh mlflow pmml` is equal to `./create_environment.sh`

There is also parameter `-e` that stops nussknacker from running and doesn't compile prinz.

However, current solution has one downside. Both compopse files for pmml and mlflow have separated proxy containers.

2021-03-05 17:20 UTC, kantoniak commented on dev-environment/create_environment.sh
> +    echo "COOOOOMPILE"
Leftovers? 😄

2021-03-05 17:23 UTC, kantoniak commented
I didn't dive into the code too much, but building only required services _may_ solve the problem you mentioned.

2021-03-06 10:13 UTC, avan1235 requested changes

2021-03-06 10:13 UTC, avan1235 commented on dev-environment/clear_environment.sh
> +            COMP_FILES+="-f docker-compose-pmml.yaml"
space missing here imo at the end of string

2021-03-06 10:13 UTC, avan1235 commented on .env
>  PMML_SAMPLES_PORT=5100
it is not for PMML (as I see you changed the name to NGINX_PMML_STATIC_PORT) - it is serving extra parametrs for model that are not provided for nussknacker and which should be downloaded additionally - it should be in something like 'abstract' docker comopse which can be used for mlfloe as well as for pmml as it is implemented in prinz api (not in pmml nor in mlflow)

2021-03-06 10:13 UTC, avan1235 commented on dev-environment/create_environment.sh
> +    echo "COOOOOMPILE"
to be removed

2021-03-06 10:13 UTC, avan1235 commented on dev-environment/docker-compose-pmml.yaml
> +      - "${NGINX_PMML_STATIC_PORT}:${NGINX_PMML_STATIC_PORT}"
as described - it shouldn't be here as it is not created for pmml

2021-03-06 10:13 UTC, avan1235 commented on dev-environment/nginx/pmml/templates/default.conf.template
> +}
this is not meant to be served for pmml - we use this data to test the model proxy which can add extra parameters to model so it is should be separated

2021-03-09 07:09 UTC, avan1235 approved these changes

2021-03-09 17:15 UTC, merged