Bump NU to 1.2-preview / latest staging
prinz-nussknacker/prinz pull request #207
Opened 2021-12-13 16:03 UTC by lciolecki

2021-12-13 16:18 UTC, avan1235 commented
@lciolecki thanks for your update 👌🏻 Tests are passed, there is extra newline `LoggingSinkFunction.scala` that is detected as lint error. Fix that and we could merge it as changes looks good.
btw if you need it published on GH packages with these version, then we can think of it, but we planned to publish new version with the same version of nussknacker stable versions (so e.g. when 1.2 becomes stable)

2021-12-13 16:37 UTC, lciolecki commented
If you could be so kind and publish new version after merge it, I will be thankful. We want use nu-prinz with latest nu version from staging.

2021-12-13 16:56 UTC, avan1235 commented
Ok, then let's update all places in project where you find [1.0.0-SNAPSHOT](https://github.com/prinz-nussknacker/prinz/search?q=1.0.0-SNAPSHOT) to 1.2.0-PREVIEW and we would be ready to go if no places are missed 😉 But please add this to your PR for simplicity

2021-12-13 17:33 UTC, avan1235 requested changes

2021-12-13 17:33 UTC, avan1235 commented on build.sbt
> +val nussknackerV = "1.2.0-staging-2021-12-09-5983-f15ac11992e3a82d32f651ef4e05b5d9458f46aa-SNAPSHOT"
modify also the prinz version from 1.0.0-SNAPSHOT to 1.2.0-STAGING in all places in project

2021-12-14 07:14 UTC, avan1235 approved these changes

2021-12-14 07:15 UTC, merged