MlflowDataConverter + tests
prinz-nussknacker/prinz pull request #53
Opened 2020-12-04 18:06 UTC by xvk9

Closes #39

2020-12-04 18:47 UTC, avan1235 requested changes
some discussion needed on nullability of data. small fixes requested

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/main/scala/pl/touk/nussknacker/prinz/util/converter/mlflow/MlflowDataConverter.scala
> +class MlflowDataConverter {
for  me it shoudl be an object as it takes no arguments

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/main/scala/pl/touk/nussknacker/prinz/util/converter/mlflow/MlflowDataConverter.scala
> +  implicit val encodeDecimalOrString: Encoder[Either[BigDecimal, String]] =
may they be private? don't see for now the reason to expose them globally

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/test/scala/pl/touk/nussknacker/prinz/converter/mlflow/MlflowDataConverterTest.scala
> +    val expected = SetMultimap[String, Either[BigDecimal, String]](
leave map in simple form "key" -> 42 and use map function to map your map. tests for bigger data (genarated in somehow specified way) should be added

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/test/scala/pl/touk/nussknacker/prinz/converter/mlflow/MlflowDataConverterTest.scala
> +  implicit class EitherOps[A](private val obj: A) {
should be in some util package in code as may be useful

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/main/scala/pl/touk/nussknacker/prinz/util/converter/mlflow/MlflowDataConverter.scala
> +    val data = multimap.
dots

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/main/scala/pl/touk/nussknacker/prinz/util/converter/mlflow/MlflowDataConverter.scala
> +    val dataframe = decode[Dataframe](parse(data).getOrElse(Json.Null).noSpaces).
may be at least 2 lines of code to be more readable:
val parsedData = parse(data).getOrElse(Json.Null).noSpaces
val dataframe = ...

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/main/scala/pl/touk/nussknacker/prinz/util/converter/mlflow/MlflowDataConverter.scala
> +    val dataframe = decode[Dataframe](parse(data).getOrElse(Json.Null).noSpaces).
watch out on dots at the end of the line

2020-12-04 18:47 UTC, avan1235 commented on prinz/src/main/scala/pl/touk/nussknacker/prinz/util/converter/mlflow/MlflowDataConverter.scala
> +    dataframe != null && !dataframe.data.exists(record => record.length != dataframe.columns.length)
I'm not sure if it may even be null (I know I've written this in tests samples bu tit was for some example). Need to be discussed

2020-12-05 16:40 UTC, xvk9 commented
More extensive unit tests will be added after implementing insertion ordered collections

2020-12-05 19:56 UTC, avan1235 approved these changes

2020-12-05 20:59 UTC, merged